import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { toast, ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

import CoinbaseWalletConnect from "@/components/CoinbaseWalletConnect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <ToastContainer position="top-right" />

        <div className="grid grid-cols-12">
          <div className="col-span-2">

            <ul className="flex flex-col gap-4 p-4">

              <li>
                <a href="/" className="text-blue-600 hover:underline">
                  Home
                </a>
              </li>
              <li>
                <a href="/solana-tokens" className="text-blue-600 hover:underline">
                  Solana Tokens
                </a>
              </li>
              <li>
                <a href="/base-tokens" className="text-blue-600 hover:underline">
                  Base Tokesn
                </a>
              </li>
             

              </ul>
          </div>


          <div className="col-span-10">
            {children}
          </div>
        </div>
      
      </body>
    </html>
  );
}
